config/routes.rb
Bibtuck::Application.routes.draw do

#  resources :subscribers, :only => [ :new, :create, :show ]

  match 'vogue' => 'subscribers#new', :as => :new_subscriber
  match 'vogue/signup' => 'subscribers#create', :as => :subscribers
  match 'vogue/thank-you' => 'subscribers#show', :as => :subscriber

  root :to => "home#index"
  match 'splash' => 'home#splash', :as => :splash

  get "users/index"

  resources :feedback_messages
  resources :photos do
    member do
      post :aviary_callback
    end
  end

  resources :brands
  resources :items do
    resources :buck_refunds do
      get :accept, :on => :member
      get :reject, :on => :member
      get :thank_you, :on => :member
    end
    resources :carrier_pickups
    resources :flagged_items
    member do
      get :extended_state
      get :shipping_label
      put :bib
      put :unbib
      get :quick_view
    end
  end

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {
                        :invitations   => 'invitations',
                        :registrations => 'registrations',
                        :sessions      => 'sessions'
                      }

  post 'admin/search'
  post '/search' => 'search#create'

  resources :conversations, :controller => "user_conversations" do
    resources :messages
    member do
      post :mark_as_read
      post :mark_as_unread
    end
    collection do
      post :bulk_update
    end
  end

  resources :users do
    resources :conversations, :controller => "user_conversations"
    post :resend_invite, :on => :member
    post :destroy_saved_photos, :on => :collection
    resources :addresses do
      get :set_as_primary, :on => :member
    end
    resources :experiences do
      get :thank_you, :on => :collection
    end
    member do
      get :activity
      get :account
      get :bucks
      get :saved_photos
      get :deactivate
      get :featured
      get :edit_email
      get :edit_username
      get :edit_password
      put :update_field
      put :update_password
      get :autocomplete_field_results
      get :request_shipping_boxes
      post :post_shipping_boxes_request
    end
    resources :follows, :only => [ :index ], :path => 'friends'
  end

  match '/admin' => 'admin#index'
  match 'export_orders' =>  'admin#export_orders', :as => :export_orders
  match 'export_items' =>  'admin#export_items', :as => :export_items
  match 'export_users' =>  'admin#export_users', :as => :export_users

  namespace :admin do
    resources :photos
    resources :discounts
    resources :credits
    resources :featured_closets do
      member do
        get :set_current
      end
    end
    resources :lookbook_photos
    resources :subscribers do
      get :export, :on => :collection
    end
    resources :users do
      member do
        get :activate
        get :deactivate_popup
        post :deactivate
      end
    end
    resources :brands
    resources :items do
      member do
        get :change_state
      end
    end
    resources :messages
    resources :flagged_items
    resources :registration_codes
    resources :recommendations
    resources :parameters
    resources :orders do
      member do
        get :edit_address
        post :update_address
      end
    end
    resources :shipping_boxes do
      member do
        post :set_amounts
      end
    end
  end

  resources :carts
  resources :orders do
    member do
      get :express
      get :setaddress
      get :complete
      get :wepayauth
    end
  end
  resources :signups
  resources :buck_purchases do
    collection do
      get :express
      get :complete
      get :not_enough
      get :select_payment_option
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :follows, :only => [ :create, :destroy ]
  resources :pages

  %w(
    about
    contact_us
    how_it_works
    q_and_a
    legal_stuff
    shipping_and_transaction_info
    shipping_from_info
    shipping_box_info
    community_guidelines
    photo_tips
  ).each { |path|
    match "pages/#{path.gsub('_','-')}" => 'high_voltage/pages#show',
          :id => path
  }
  
  match '*a', :to => 'errors#routing'

end

app/controllers/buck_purchases_controller.rb
class BuckPurchasesController < ApplicationController
  before_filter :authenticate_user!

  def new
    @buck_purchase = BuckPurchase.new(params[:buck_purchase])
    @ref_page = params[:ref_page]
    respond_to do |format|
      format.html { render :layout => 'popup' }
      format.js
    end
  end

  def not_enough
    @buck_purchase = BuckPurchase.new(params[:buck_purchase])
    @item = Item.find_by_id(params[:item_id])
    @difference = current_cart.amount_needed(current_user, @item)
    @ref_page = :not_enough
    render :layout => 'popup'
  end

  def select_payment_option
    buck_params = params[:buck_purchase] || {}
    buck_params[:bucks] = buck_params[:bucks] == 'Other' ? params[:bucks_other] : buck_params[:bucks]
    @amount = BuckPurchase.bucks_to_cents(buck_params[:bucks])
    @return_params = {
      'bucks' => buck_params[:bucks].to_i,
      'item_id' => params[:item_id],
      'ref_page' => params[:ref_page]
    }
    if @amount > 0
      @amount /= 100.0
      wepay = WePay.new(WEPAY_OPTIONS[:client_id], WEPAY_OPTIONS[:secret], WEPAY_OPTIONS[:use_stage])
      wepay_params = {
        :account_id => WEPAY_OPTIONS[:account_id],
        :amount => @amount,
        :short_description => "Buying #{buck_params[:bucks]}.",
        :fee_payer => :Payee,
        :type => :SERVICE,
        :mode => :iframe,
        :redirect_uri => complete_buck_purchases_url(@return_params)
      }
      @wepaycheckout = wepay.call('/checkout/create', WEPAY_OPTIONS[:access_token], wepay_params)
      render :layout => 'popup'
    else
      render :text => "Wrong amount."
    end
  end

  def express
    amount = BuckPurchase.bucks_to_cents(params[:bucks].to_i)
    if amount > 0
      return_params = {
        'bucks' => params[:bucks],
        'item_id' => params[:item_id],
        'ref_page' => params[:ref_page]
      }
      res = EXPRESS_GATEWAY.setup_purchase(amount,
        :ip                => request.remote_ip,
        :return_url        => complete_buck_purchases_url(return_params),
        :cancel_return_url => root_url
      )
      redirect_to EXPRESS_GATEWAY.redirect_url_for(res.token)
    else
      flash[:notice] = "Error processing your payment."
      redirect_to case params[:ref_page]
      when 'not_enough'
        cart_path(current_user)
      when 'q_and_a'
        page_path('q_and_a')
      when 'my_profile'
        user_path(current_user)
      else
        items_path
      end
    end
  end

  def complete
    @user = current_user
    @buck_purchase = BuckPurchase.new(:bucks => params[:bucks])
    @buck_purchase.user = @user
    @buck_purchase.ip_address = request.ip
    if params[:checkout_id]
      # WePay complete
      @buck_purchase.wepay_checkout_id = params[:checkout_id]
    elsif params[:token]
      # PayPal complete
      @buck_purchase.express_token = params[:token]
      @buck_purchase.express_payer_id = params['PayerID']
      @buck_purchase.wepay_checkout_id = nil
    else
      flash[:notice] = 'There was an error with your payment.'
      redirect_to cart_path(@user)
      return
    end

    if @buck_purchase.save
      if @buck_purchase.wepay_checkout_id
        # wepay
        wepay = WePay.new(WEPAY_OPTIONS[:client_id], WEPAY_OPTIONS[:secret], WEPAY_OPTIONS[:use_stage])
        response = wepay.call('/checkout', WEPAY_OPTIONS[:access_token], {
          checkout_id: params[:checkout_id]
        })
        if %w(authorized reserved captured settled).include? response['state']
          @buck_purchase.after_purchase
          flash[:popup_notice] = {:id => 'buck_purchase_ok', :amount => @buck_purchase.bucks}
        else
          flash[:notice] = 'There was an error with your payment.'
        end
      else
        # paypal
        if @buck_purchase.purchase
          flash[:popup_notice] = {:id => 'buck_purchase_ok', :amount => @buck_purchase.bucks}
        else
          flash[:notice] = "There was an error making the purchase."
        end
      end
    else
      flash[:notice] = "There was an error with your order."
    end

    case params[:ref_page]
    when 'not_enough'
      if params[:item_id]
        item = Item.find_by_id(params[:item_id])
        if item
          if current_user.can_afford?(item) && !Cart.item_in_any_cart?(item)
            current_cart.add_item(item)
          else
            redirect_to item
            return
          end
        end
      end
      redirect_to cart_path(current_user)
    when 'q_and_a'
      redirect_to page_path('q_and_a')
    when 'my_profile'
      redirect_to current_user
    else
      redirect_to items_path
    end
  end
end

app/views/buck_purchases/_form.html.haml
= hidden_field_tag :ref_page, @ref_page
%table
  %thead
    %th Bucks
    %th Price
  %tbody
    - is_selected = false
    - BuckPurchase::PRESET_BUCK_PURCHASES.each do |bucks, cents|
      %tr
        %td.selection
          - if !is_selected && (cents/100.0 >= difference)
            = f.radio_button :bucks, bucks, :checked => true
            - is_selected = true
          - else
            = f.radio_button :bucks, bucks
          == #{bucks} Bucks
        %td.amount= number_to_currency(cents.to_f / 100)
    %tr
      %td.selection
        = f.radio_button :bucks, 'Other', :checked => !is_selected
        Other:
        - if is_selected
          = text_field_tag :bucks_other
        - else
          = text_field_tag :bucks_other, difference.to_i
        = link_to "Compute", '', :id => :compute_bucks
      %td#price.amount= is_selected ? number_to_currency(@buck_purchase.price) : number_to_currency(BuckPurchase.bucks_to_cents(difference)/100.0)

= content_for :js do
  :javascript
    $('#compute_bucks').click(function() {
      $('#buck_purchase_bucks_other', this.parentNode).prop('checked', true);
      $('#buck_purchase_bucks_final').val($('#bucks_other').val());
      $.ajax({
        url:  '/buck_purchases/new.js',
        type: 'GET',
        data: { "buck_purchase[bucks]" : $('#bucks_other').val() }
      });
      return false;
    });
    $('#bucks_other').change(function() {
      $('#buck_purchase_bucks_other', this.parentNode).prop('checked', true);
    });

app/views/buck_purchases/complete.html.haml
#buck_transaction_complete_page
  = sidebar

  #main
    %h1 Thank you for your payment!

    %p Your transaction has been completed, and a receipt for your purchase has been emailed to you.

app/views/buck_purchases/new.html.haml
#buy_bucks_popup
  %h1 Buy Bucks
  .note Not enough Bucks to purchase an item? Buy some here.
  = form_for @buck_purchase, :url => select_payment_option_buck_purchases_path, :html => { :method => :get } do |f|
    #buck_transaction_form
      = render :partial => 'form', :locals => {:f => f}
    #buck_actions
      = content_tag :button, 'Buy Bucks', :type => :submit, :class => :grey_button
= content_for :js do
  :javascript
    $(function() {
      var form = $('#facebox form#new_buck_purchase');
      $('button[type="submit"]').click(function(e) {
        e.preventDefault();
        var submitUrl = '#{select_payment_option_buck_purchases_url}' + '?' + form.serialize();
        $.facebox({ajax: submitUrl, popupwidth: 600});
        return false;
      });
    });

app/views/buck_purchases/new.js.haml
$('#price').html('#{number_to_currency(@buck_purchase.price)}');
$('#bucks_final').val('#{@buck_purchase.bucks}');

app/views/buck_purchases/not_enough.html.haml
.not_enough_bucks_popup
  %h2 Not enough bucks!
  .note You currently have #{number_to_bucks current_user.buck_balance} in your account. You need #{number_to_bucks @difference, :none} more to buy these items.
  = form_for @buck_purchase, :url => select_payment_option_buck_purchases_path, :html => { :method => :get } do |f|
    - if @item
      = hidden_field_tag :item_id, @item.id
    #buck_transaction_form
      = render :partial => 'form', :locals => { :f => f, :difference => @difference }
    #buck_actions
      = content_tag :button, 'Buy Now', :type => :submit, :class => :grey_button
      -if @item
        = link_to 'Add to cart and buy later', cart_path(current_user, :item_id => @item.id, :no_popup => true),
          :method => :put, :rel => 'nofollow', :class => [:add_to_cart_not_enough, :grey_button]

= content_for :js do
  :javascript
    $(function() {
      $('#facebox a.add_to_cart_not_enough').click(function() {
        $.facebox.close();
        return true;
      });
      var form = $('#facebox form#new_buck_purchase');
      $('button[type="submit"]').click(function(e) {
        e.preventDefault();
        var submitUrl = '#{select_payment_option_buck_purchases_url}' + '?' + form.serialize();
        $.facebox({ajax: submitUrl, popupwidth: 600});
        return false;
      });
    });

app/views/buck_purchases/select_payment_option.html.haml
#select_payment_option_popup
  %h2 Enter Payment Details
  #select_payment
    - if @wepaycheckout['checkout_id']
      #wepay_checkout
      #paypal_checkout
        OR -
        = link_to image_tag('buttons/checkout_with_paypal.gif'), express_buck_purchases_path(@return_params)
        = content_for :js do
          :javascript
            $(function() {
              WePay.iframe_checkout("wepay_checkout", "#{@wepaycheckout['checkout_uri']}");
            });
    - else
      #paypal_checkout
        = link_to image_tag('buttons/checkout_with_paypal.gif'), express_buck_purchases_path(@return_params)