config/routes.rb
Bibtuck::Application.routes.draw do

#  resources :subscribers, :only => [ :new, :create, :show ]

  match 'vogue' => 'subscribers#new', :as => :new_subscriber
  match 'vogue/signup' => 'subscribers#create', :as => :subscribers
  match 'vogue/thank-you' => 'subscribers#show', :as => :subscriber

  root :to => "home#index"
  match 'splash' => 'home#splash', :as => :splash

  get "users/index"

  resources :feedback_messages
  resources :photos do
    member do
      post :aviary_callback
    end
  end

  resources :brands
  resources :items do
    resources :buck_refunds do
      get :accept, :on => :member
      get :reject, :on => :member
      get :thank_you, :on => :member
    end
    resources :carrier_pickups
    resources :flagged_items
    member do
      get :extended_state
      get :shipping_label
      put :bib
      put :unbib
      get :quick_view
    end
  end

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {
                        :invitations   => 'invitations',
                        :registrations => 'registrations',
                        :sessions      => 'sessions'
                      }

  post 'admin/search'
  post '/search' => 'search#create'

  resources :conversations, :controller => "user_conversations" do
    resources :messages
    member do
      post :mark_as_read
      post :mark_as_unread
    end
    collection do
      post :bulk_update
    end
  end

  resources :users do
    resources :conversations, :controller => "user_conversations"
    post :resend_invite, :on => :member
    post :destroy_saved_photos, :on => :collection
    resources :addresses do
      get :set_as_primary, :on => :member
    end
    resources :experiences do
      get :thank_you, :on => :collection
    end
    member do
      get :activity
      get :account
      get :bucks
      get :saved_photos
      get :deactivate
      get :featured
      get :edit_email
      get :edit_username
      get :edit_password
      put :update_field
      put :update_password
      get :autocomplete_field_results
      get :request_shipping_boxes
      post :post_shipping_boxes_request
    end
    resources :follows, :only => [ :index ], :path => 'friends'
  end

  match '/admin' => 'admin#index'
  match 'export_orders' =>  'admin#export_orders', :as => :export_orders
  match 'export_items' =>  'admin#export_items', :as => :export_items
  match 'export_users' =>  'admin#export_users', :as => :export_users

  namespace :admin do
    resources :photos
    resources :discounts
    resources :credits
    resources :featured_closets do
      member do
        get :set_current
      end
    end
    resources :lookbook_photos
    resources :subscribers do
      get :export, :on => :collection
    end
    resources :users do
      member do
        get :activate
        get :deactivate_popup
        post :deactivate
      end
    end
    resources :brands
    resources :items do
      member do
        get :change_state
      end
    end
    resources :messages
    resources :flagged_items
    resources :registration_codes
    resources :recommendations
    resources :parameters
    resources :orders do
      member do
        get :edit_address
        post :update_address
      end
    end
    resources :shipping_boxes do
      member do
        post :set_amounts
      end
    end
  end

  resources :carts
  resources :orders do
    member do
      get :express
      get :setaddress
      get :complete
      get :wepayauth
    end
  end
  resources :signups
  resources :buck_purchases do
    collection do
      get :express
      get :complete
      get :not_enough
      get :select_payment_option
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :follows, :only => [ :create, :destroy ]
  resources :pages

  %w(
    about
    contact_us
    how_it_works
    q_and_a
    legal_stuff
    shipping_and_transaction_info
    shipping_from_info
    shipping_box_info
    community_guidelines
    photo_tips
  ).each { |path|
    match "pages/#{path.gsub('_','-')}" => 'high_voltage/pages#show',
          :id => path
  }
  
  match '*a', :to => 'errors#routing'

end

app/controllers/admin/shipping_boxes_controller.rb
class Admin::ShippingBoxesController < AdminController

  def index
    @box_sizes = Category::BOX_SIZES_ENDICIA
    @totals = [] 
    User.where(:last_sign_in_at.ne => nil).each do |user|
      address = user.shipping_box_deliveries.first.try(:address) || user.primary_shipping_address || (user.shipping_addresses.count == 1 ? user.shipping_addresses.first : nil)
      next unless address
      sold_items = {}
      sent_boxes = {}
      remaining_boxes = {}
      @box_sizes.each do |size, label|
        sold_items[size] = Item.where(:user => user, :tucked_at.ne => nil, :shipping_box_size => size).count
        sent_boxes[size] = user.shipping_box_amount_delivered(size)
        remaining_boxes[size] = sent_boxes[size] - sold_items[size]
      end
      @totals << {
        :user => user,
        :address => address,
        :sold => sold_items,
        :sent => sent_boxes,
        :remaining => remaining_boxes,
        :sent_at => ShippingBoxDelivery.where(:user => user).maximum(:sent_at),
        :requested_at => ShippingBoxDelivery.where(:user => user).minimum(:requested_at)
      }
    end
    @totals.sort! do |t1, t2|
      if t1[:requested_at]
        if t2[:requested_at]
          t1[:requested_at] <=> t2[:requested_at]
        else
          -1
        end
      elsif t2[:requested_at]
        1
      else
        t1[:remaining].values.sum <=> t2[:remaining].values.sum
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    @box_sizes = Category::BOX_SIZES_ENDICIA
    @boxes = []
    @box_sizes.each do |size, label|
      items_sold = Item.where(:user => @user, :tucked_at.ne => nil, :shipping_box_size => size).count
      sent_boxes = @user.shipping_box_amount_delivered(size)
      @boxes << {
        :size => size,
        :label => label,
        :remaining => sent_boxes - items_sold
      }
    end
    render :layout => 'popup'
  end

  def set_amounts
    @user = User.find(params[:id])
    if @user
      box_sizes = Category::BOX_SIZES_ENDICIA
      box_sizes.each do |size, label|
        box_amount = params[:box][size]
        if box_amount
          delivery = @user.shipping_box_deliveries.find_by_box_size(size)
          if delivery
            delivery.update_attributes :amount => (delivery.amount + box_amount.to_i), :sent_at => Time.now, :requested_at => nil
          else
            @user.shipping_box_deliveries.create(:box_size => size, :amount => box_amount.to_i, :sent_at => Time.now)
          end
        end
      end
    end
    redirect_to admin_shipping_boxes_path
  end

end

app/views/admin/shipping_boxes/edit.html.haml
.line Set total amounts of boxes sent to user:
.line= @user.display_name
.shipping_box_form
  = form_tag set_amounts_admin_shipping_box_path(@user.id) do |f|
    - @boxes.each do |box|
      = label_tag "Box size #{box[:size]}"
      = text_field :box, box[:size]
      %span.remaining Remaining: #{box[:remaining]}
    .actions
      = content_tag :button, 'Save', :type => :submit, :class => :grey_button

app/views/admin/shipping_boxes/index.html.haml
.menu_bar
.shipping_boxes_index
  %table.admin_list_table
    %thead
      %tr
        %th{ :colspan => 3 } User
        %th{ :colspan => @box_sizes.length } Items sold
        %th{ :colspan => @box_sizes.length } Boxes sent
        %th{ :colspan => @box_sizes.length } Remaining boxes
        %th Requested at
        %th Sent at
        %th.actions
      %tr
        %th ID
        %th Name
        %th Address
        - 3.times do
          - @box_sizes.each do |size, label|
            %th.size= size
        %th
        %th
        %th.actions
    %tbody
      - @totals.each do |t|
        %tr
          %td= t[:user].id
          %td
            .line= link_to t[:user].display_name, admin_user_path(t[:user])
            .line= mail_to t[:user].email
          %td
            - if addr = t[:address]
              .line #{addr.first_name} #{addr.last_name}
              .line #{addr.street_line1}
              - if addr.street_line2
                .line #{addr.street_line2}
              .line #{addr.city}, #{addr.state} #{addr.zipcode}
              - if addr.phone
                .line #{addr.phone}
          - @box_sizes.each do |size, label|
            %td.count= t[:sold][size]
          - @box_sizes.each do |size, label|
            %td.count= t[:sent][size]
          - @box_sizes.each do |size, label|
            %td.count= t[:remaining][size]
          %td.date= format_date t[:requested_at]
          %td.date= format_date t[:sent_at]
          %td.actions
            = link_to 'Send boxes', edit_admin_shipping_box_path(t[:user].id), :rel => 'facebox.shipping_box_form'