config/routes.rb
Bibtuck::Application.routes.draw do

#  resources :subscribers, :only => [ :new, :create, :show ]

  match 'vogue' => 'subscribers#new', :as => :new_subscriber
  match 'vogue/signup' => 'subscribers#create', :as => :subscribers
  match 'vogue/thank-you' => 'subscribers#show', :as => :subscriber

  root :to => "home#index"
  match 'splash' => 'home#splash', :as => :splash

  get "users/index"

  resources :feedback_messages
  resources :photos do
    member do
      post :aviary_callback
    end
  end

  resources :brands
  resources :items do
    resources :buck_refunds do
      get :accept, :on => :member
      get :reject, :on => :member
      get :thank_you, :on => :member
    end
    resources :carrier_pickups
    resources :flagged_items
    member do
      get :extended_state
      get :shipping_label
      put :bib
      put :unbib
      get :quick_view
    end
  end

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {
                        :invitations   => 'invitations',
                        :registrations => 'registrations',
                        :sessions      => 'sessions'
                      }

  post 'admin/search'
  post '/search' => 'search#create'

  resources :conversations, :controller => "user_conversations" do
    resources :messages
    member do
      post :mark_as_read
      post :mark_as_unread
    end
    collection do
      post :bulk_update
    end
  end

  resources :users do
    resources :conversations, :controller => "user_conversations"
    post :resend_invite, :on => :member
    post :destroy_saved_photos, :on => :collection
    resources :addresses do
      get :set_as_primary, :on => :member
    end
    resources :experiences do
      get :thank_you, :on => :collection
    end
    member do
      get :activity
      get :account
      get :bucks
      get :saved_photos
      get :deactivate
      get :featured
      get :edit_email
      get :edit_username
      get :edit_password
      put :update_field
      put :update_password
      get :autocomplete_field_results
      get :request_shipping_boxes
      post :post_shipping_boxes_request
    end
    resources :follows, :only => [ :index ], :path => 'friends'
  end

  match '/admin' => 'admin#index'
  match 'export_orders' =>  'admin#export_orders', :as => :export_orders
  match 'export_items' =>  'admin#export_items', :as => :export_items
  match 'export_users' =>  'admin#export_users', :as => :export_users

  namespace :admin do
    resources :photos
    resources :discounts
    resources :credits
    resources :featured_closets do
      member do
        get :set_current
      end
    end
    resources :lookbook_photos
    resources :subscribers do
      get :export, :on => :collection
    end
    resources :users do
      member do
        get :activate
        get :deactivate_popup
        post :deactivate
      end
    end
    resources :brands
    resources :items do
      member do
        get :change_state
      end
    end
    resources :messages
    resources :flagged_items
    resources :registration_codes
    resources :recommendations
    resources :parameters
    resources :orders do
      member do
        get :edit_address
        post :update_address
      end
    end
    resources :shipping_boxes do
      member do
        post :set_amounts
      end
    end
  end

  resources :carts
  resources :orders do
    member do
      get :express
      get :setaddress
      get :complete
      get :wepayauth
    end
  end
  resources :signups
  resources :buck_purchases do
    collection do
      get :express
      get :complete
      get :not_enough
      get :select_payment_option
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :follows, :only => [ :create, :destroy ]
  resources :pages

  %w(
    about
    contact_us
    how_it_works
    q_and_a
    legal_stuff
    shipping_and_transaction_info
    shipping_from_info
    shipping_box_info
    community_guidelines
    photo_tips
  ).each { |path|
    match "pages/#{path.gsub('_','-')}" => 'high_voltage/pages#show',
          :id => path
  }
  
  match '*a', :to => 'errors#routing'

end

app/views/notifier/buck_purchase.html.haml
%p Thank you for your buck purchase! With more bucks to spend, we know you'll find a great addition to your closet.

%p Happy Bib + Tucking!

app/views/notifier/buck_refund_rejected.html.haml
%p User #{@buck_refund.user.display_name} has rejected a refund for the following reason:

%p #{@buck_refund.seller_comment}

Thanks,
B+T

app/views/notifier/buck_refund_request.html.haml
#{@requester.display_name} has requested a buck refund for item #{@item.name}.

Click #{link_to 'here', edit_item_buck_refund_url(@item, @buck_refund)} to find out details.

Please note that accepting a buck refund request does not imply the item will be sent back to you.

If you have any questions, email us at #{mail_to 'help@bibandtuck.com'} or call us at #{BT_PHONE_NUMBER}.

xo

The B+T Team

app/views/notifier/editors_pick.html.haml
%p Hi #{@item.user.first_name},

%p We just wanted to let you know that we've selected your #{link_to @item.name, item_url(@item)} as an #{link_to "Editor's Pick", items_url(:filter => :editors_picks)} on Bib + Tuck. Thanks for lending your impeccable style to the site and curating such a hot closet.

%p xo,
%p The B+T Team

app/views/notifier/feedback_message.html.haml
%p Customer Feedback

%p== Email: #{@feedback_message.email}
%p== Content: #{@feedback_message.body}

app/views/notifier/flagged_item.text.haml
The following item has been flagged for removal:

== Item Name: #{@item.name}
== Seller: #{@item.user.display_name}
== Flagged on: #{bt_timestamp @flagged_item.created_at}
== Item: #{link_to 'item', item_url(@item)}

app/views/notifier/invitation_accepted.html.haml
%p Hi #{@inviter.full_name},

%p
  #{link_to @new_user.full_name, user_url(@new_user)} has accepted your
  invitation to Bib + Tuck.

%p
  We value your impeccable taste in clothes as well as friends- we just
  know #{link_to @new_user.full_name, user_url(@new_user)} is going to be
  a great addition to our community and we'd like to thank you by adding
  #{BuckTransaction::POINTS[:invitation]} bucks to your account.
%p= link_to 'Now go tucking, right this way...', items_url

%p xo,
%p The B+T Team

app/views/notifier/new_follower.html.haml
%p Hey #{@follow.following.first_name}!

%p #{link_to @follow.follower.display_name, user_url(@follow.follower)} is now following you on Bib + Tuck.

- if @follow.follower.about_me.present?
  %p About your admirer: #{@follow.follower.about_me}

%p Check out what she's bibbed #{link_to 'here', user_url(@follow.follower)}.

%p xo,
%p The B+T Team

app/views/notifier/new_message.html.haml
%p #{@message.user.display_name} says:

%p= @message.body

%p== To reply, go here: #{user_conversation_url(@user, @message.conversation.id)}

app/views/notifier/notify_seller_to_ship.html.haml
%p Hi #{@seller.first_name},

%p #{@item.order.user.display_name} is ever so patiently awaiting the #{link_to @item.name, item_url(@item)}. We know you're busy, but please ship it soon, or #{link_to 'contact her', user_url(@item.order.user)} to let her know what's going on.

%p #{link_to 'Click here', shipping_label_item_url(@item)} to print your shipping label.

%p If you need help, feel free to email us at #{mail_to 'help@bibandtuck.com'} or call us at (646) 568-5666.
%p - The B+T Team

app/views/notifier/shipped_item.html.haml
%p Hi #{@buyer.first_name},

%p
  Your purchase of #{@item.name} is now on its way to you. It'll be with you soon,
  but if you want to keep an eye on it you can click #{link_to 'here', @tracking_url} to follow its journey. 

%p Your USPS tracking number is: #{@tracking_number}

%p Happy Tucking!

%p - The B+T Team

app/views/notifier/tucked_for_buyer.html.haml
- single = (@order.items.count == 1)
%p Hi #{@order.user.first_name},

%p What a great tuck!

%p Here is everything you need to know about your#{single ? '' : ' Bib + Tuck'} purchase:

%p <b>YOUR ORDER NUMBER IS:</b>
%p= @order.id
%p <b>YOU PURCHASED:</b>
- @order.items.each do |item|
  %p #{link_to item.name, item_url(item)} for #{number_to_bucks item.price}
%p <b>YOUR #{single ? 'ITEM' : 'ITEMS'} WILL BE DELIVERED TO:</b>
%p
  #{@order.to_addr_first_name} #{@order.to_addr_last_name}<br/>
  #{@order.to_addr_street_line1}<br/>
  - if @order.to_addr_street_line2.present?
    #{@order.to_addr_street_line2}<br/>
  #{@order.to_addr_city}, #{@order.to_addr_state} #{@order.to_addr_zipcode}
%p <b>AND HERE'S WHAT HAPPENS NEXT:</b>
%ul
  - if single
    - seller = @order.items.first.user
    %li #{seller.display_name} has received an email with a prepaid mailing label so she can send you the item.
    %li You can visit #{link_to 'My Activity', activity_user_url(@order.user, :anchor => 'purchased')} to track the status of your purchase at any time. If the item has not been shipped, feel free to message #{link_to seller.display_name, user_url(seller)}.
  - else
    %li The sellers have received emails with prepaid mailing labels so that they can send you the items.
    %li You can visit #{link_to 'My Activity', activity_user_url(@order.user, :anchor => 'purchased')} to track your purchases at any time. If the items have not been shipped, feel free to message the sellers through their profiles.

%p If you have any questions, email us at #{mail_to 'help@bibandtuck.com'} or call us at (646) 568-5666.

%p Happy Tucking!
%p - The B+T Team

app/views/notifier/tucked_for_seller.html.haml
%p Hi #{@seller.first_name},

%p We think you have a covetous closet and #{link_to @buyer.display_name, user_url(@buyer)}#{@buyer.short_bio.present? ? ", a #{@buyer.short_bio}" : ''} thinks so too. She just tucked your #{link_to @item.name, item_url(@item)} for #{number_to_bucks @item.price}.

%p What now?

%ul
  %li <b>PACK YOUR GARMENT.</b> Make sure to use USPS Regional Rate Box #{@item.shipping_box_size.upcase}. Your item won't ship if you use a different box. Out of shipping boxes? Visit your #{link_to 'Account Settings', account_user_url(@seller)} to request more boxes and we'll send them your way.
  %li <b>PRINT YOUR SHIPPING LABEL</b>#{@item.order_item.shipping_label.present? ? ' (attached)' : ''}. You can also access your label by visiting #{link_to 'My Activity', activity_user_url(@seller, :anchor => 'sold')}.
  %li <b>SHIP FAST!</b> Then, go find yourself a great #{link_to 'tuck', items_url}.

%p
  If you'd like to schedule a USPS carrier pickup, #{link_to 'click here', URL_SHIPPING_PICKUP_ORDER}.
  %br/
  To find your closest USPS drop-off location, #{link_to 'click here', URL_SHIPPING_DROPOFF_LOCATIONS}.

%p If you need help, feel free to email us at #{mail_to 'help@bibandtuck.com'} or call us at (646) 568-5666.

%p xo,
%p The B+T Team

app/views/notifier/welcome_user.html.haml
%p Hi #{@user.first_name},

Welcome to Bib + Tuck! We're jumping off our office chairs excited to peak inside your wardrobe.

%p First, take a second to #{link_to 'complete your profile', edit_user_url(@user)}. Fashion is all about the fashionista. We actually want to get to know you.

%p Get ready to play! There are hundreds of fabulous items for you to #{link_to 'tuck', items_url} (purchase), and we're giving you 50 free bucks just because we love you.

%p But don't just tuck with us. #{link_to 'Bib', new_item_url} (upload/sell) your own items to earn more bucks. Please bib carefully; the items you sell will help set the tone for the whole community. Someone will lovingly tuck them soon.

%p And don't worry, you'll be hip with the lingo in no time.

%p Lastly, spread the word! If you could raid 3 of your friend's closets, who would they be? #{link_to 'Send them an invitation', new_user_invitation_url} and get 25 bucks each time one of them joins us. See, we really do love you.

%p xo,
%p Sari and Sari