config/routes.rb
Bibtuck::Application.routes.draw do

#  resources :subscribers, :only => [ :new, :create, :show ]

  match 'vogue' => 'subscribers#new', :as => :new_subscriber
  match 'vogue/signup' => 'subscribers#create', :as => :subscribers
  match 'vogue/thank-you' => 'subscribers#show', :as => :subscriber

  root :to => "home#index"
  match 'splash' => 'home#splash', :as => :splash

  get "users/index"

  resources :feedback_messages
  resources :photos do
    member do
      post :aviary_callback
    end
  end

  resources :brands
  resources :items do
    resources :buck_refunds do
      get :accept, :on => :member
      get :reject, :on => :member
      get :thank_you, :on => :member
    end
    resources :carrier_pickups
    resources :flagged_items
    member do
      get :extended_state
      get :shipping_label
      put :bib
      put :unbib
      get :quick_view
    end
  end

  resources :authentications
  match '/auth/:provider/callback' => 'authentications#create'

  devise_for :users, :controllers => {
                        :invitations   => 'invitations',
                        :registrations => 'registrations',
                        :sessions      => 'sessions'
                      }

  post 'admin/search'
  post '/search' => 'search#create'

  resources :conversations, :controller => "user_conversations" do
    resources :messages
    member do
      post :mark_as_read
      post :mark_as_unread
    end
    collection do
      post :bulk_update
    end
  end

  resources :users do
    resources :conversations, :controller => "user_conversations"
    post :resend_invite, :on => :member
    post :destroy_saved_photos, :on => :collection
    resources :addresses do
      get :set_as_primary, :on => :member
    end
    resources :experiences do
      get :thank_you, :on => :collection
    end
    member do
      get :activity
      get :account
      get :bucks
      get :saved_photos
      get :deactivate
      get :featured
      get :edit_email
      get :edit_username
      get :edit_password
      put :update_field
      put :update_password
      get :autocomplete_field_results
      get :request_shipping_boxes
      post :post_shipping_boxes_request
    end
    resources :follows, :only => [ :index ], :path => 'friends'
  end

  match '/admin' => 'admin#index'
  match 'export_orders' =>  'admin#export_orders', :as => :export_orders
  match 'export_items' =>  'admin#export_items', :as => :export_items
  match 'export_users' =>  'admin#export_users', :as => :export_users

  namespace :admin do
    resources :photos
    resources :discounts
    resources :credits
    resources :featured_closets do
      member do
        get :set_current
      end
    end
    resources :lookbook_photos
    resources :subscribers do
      get :export, :on => :collection
    end
    resources :users do
      member do
        get :activate
        get :deactivate_popup
        post :deactivate
      end
    end
    resources :brands
    resources :items do
      member do
        get :change_state
      end
    end
    resources :messages
    resources :flagged_items
    resources :registration_codes
    resources :recommendations
    resources :parameters
    resources :orders do
      member do
        get :edit_address
        post :update_address
      end
    end
    resources :shipping_boxes do
      member do
        post :set_amounts
      end
    end
  end

  resources :carts
  resources :orders do
    member do
      get :express
      get :setaddress
      get :complete
      get :wepayauth
    end
  end
  resources :signups
  resources :buck_purchases do
    collection do
      get :express
      get :complete
      get :not_enough
      get :select_payment_option
    end
  end

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :follows, :only => [ :create, :destroy ]
  resources :pages

  %w(
    about
    contact_us
    how_it_works
    q_and_a
    legal_stuff
    shipping_and_transaction_info
    shipping_from_info
    shipping_box_info
    community_guidelines
    photo_tips
  ).each { |path|
    match "pages/#{path.gsub('_','-')}" => 'high_voltage/pages#show',
          :id => path
  }
  
  match '*a', :to => 'errors#routing'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :discount

  has_one :buck_transactions, :as => :reference
  has_many :order_items, :dependent => :destroy
  has_many :items, :through => :order_items

  before_save :set_totals

  validates_presence_of :user
  validates_presence_of :to_addr_first_name, :to_addr_last_name
  validates_presence_of :to_addr_street_line1, :to_addr_city, :to_addr_state, :to_addr_zipcode

  TRANSACTION_FEE_IN_CENTS = 300

  attr_accessor :discount_code
  attr_reader :discount_code_error

  include Orderable

  def to_addr
    address = Address.new
    %w(first_name last_name street_line1 street_line2 city state zipcode phone).each do |attr|
      address[attr] = read_attribute("to_addr_#{attr}")
    end
    return address
  end

  def to_addr=(address)
    %w(id first_name last_name street_line1 street_line2 city state zipcode phone).each do |attr|
      write_attribute "to_addr_#{attr}", address.try(attr)
    end
  end

  def calculate_bucks
    order_items.map(&:item).map(&:price).sum
  end

  def calculate_shipping_cost
    if discount.try(:free_shipping?)
      return 0
    end
    order_items.map(&:item).map(&:shipping_fee_in_cents).sum
  end

  def calculate_transaction_fee
    if discount.try(:free_transaction?)
      return 0
    end
    order_items.map(&:item).map(&:transaction_fee_in_cents).sum
  end

  def total
    amount_in_cents / 100
  end

  def total_bucks
    order_items.map(&:item).map(&:price).sum
  end

  def shipping_cost
    shipping_cost_in_cents / 100
  end

  def transaction_fee
    transaction_fee_in_cents / 100
  end

  def total_fees
    shipping_cost_in_cents + transaction_fee_in_cents
  end

  def set_totals
    self.bucks_total = calculate_bucks
    self.shipping_cost_in_cents = calculate_shipping_cost
    self.transaction_fee_in_cents = calculate_transaction_fee
    self.amount_in_cents = shipping_cost_in_cents + transaction_fee_in_cents
  end

  def after_purchase
    return false if is_complete?

    Notifier.tucked_for_buyer(self).deliver

    Order.transaction do
      set_totals
      order_items.each do |order_item|
        order_item.item.tuck!(self)
        order_item.generate_shipping_label!(false)
        Notifier.tucked_for_seller(order_item).deliver
      end

      if user.invited_by.present? && user.orders.blank?
        BuckTransaction.create(:user => user,
                               :reason => :invitee_tuck,
                               :reference => self,
                               :delta => BuckTransaction::POINTS[:invitee_tuck])
      end

      BuckTransaction.create(:user => user,
                             :reason => :tuck_buyer,
                             :reference => self,
                             :delta => -1 * total_bucks)

      update_attribute(:to_addr_id, nil)
      update_attribute(:is_complete, true)
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < AdminController

  def index
    @orders = Order.where(:is_complete => true).order('created_at DESC')
  end

  def show
    @order = Order.find(params[:id])
  end

  def edit_address
    case params[:type]
    when 'from'
      @target = OrderItem.find(params[:id])
      @address = @target.from_addr
      @type = 'from'
    when 'to'
      @target = Order.find(params[:id])
      @address = @target.to_addr
      @type = 'to'
    end
    render :layout => 'popup'
  end

  def update_address
    @address = Address.new(params[:address])
    case params[:type]
    when 'from'
      @target = OrderItem.find(params[:id])
      @target.from_addr = @address
    when 'to'
      @target = Order.find(params[:id])
      @target.to_addr = @address
    end
    if @target.save
      flash[:notice] = 'Address saved successfully.'
    else
      flash[:notice] = 'There was error saving address.'
    end
    if params[:referrer]
      redirect_to params[:referrer]
    else
      redirect_to :back
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_filter :authenticate_user!

  def new
    @user = current_user
    if params[:discount_code] || params[:new_address]
      @order = @user.orders.where(:is_complete => nil).first
    else
      @user.orders.where(:is_complete => nil).each do |unfinished_order|
        unfinished_order.destroy
      end
    end

    unless @order
      @order = @user.orders.new(params[:order])
      @order.to_addr = @user.primary_shipping_address if @user.primary_shipping_address.present?
      current_cart.items.each do |item|
        order_item = @order.order_items.build(:order => @order, :item => item)
        order_item.from_addr = item.shipping_from_address
      end
      @order.set_totals
    end

    if @order.total_bucks > @user.buck_balance
      flash[:notice] = "You do not have enough bucks to purchase."
      redirect_to cart_path(current_cart)
    end

    if params[:discount_code]
      if @order.discount.blank?
        code = Discount.find_by_code(params[:discount_code])
        unless code && code.still_valid?
          flash[:notice] = 'Promo Code not Found.'
        else
          if code.min_amount.to_i > 0 && @order.bucks_total < code.min_amount
            flash[:notice] = "Promo Code can only be used on orders over #{code.min_amount} bucks."
          else
            @order.discount = code
            flash[:notice] = "Discount applied."
          end
        end
      end
    end

    if params[:new_address]
      shipping_address = current_user.shipping_addresses.create(params[:new_address])
      @order.to_addr = shipping_address
    end

    if @order.save(:validate => false)
      if @order.amount_in_cents > 0
        wepay = WePay.new(WEPAY_OPTIONS[:client_id], WEPAY_OPTIONS[:secret], WEPAY_OPTIONS[:use_stage])
        checkout_params = {
          :account_id => WEPAY_OPTIONS[:account_id],
          :amount => @order.amount_in_cents/100,
          :short_description => "Payment for Order No. #{@order.id}",
          :fee_payer => :Payee,
          :type => :SERVICE,
          :mode => :iframe,
          :redirect_uri => complete_order_url(@order)
        }
        @wepaycheckout = wepay.call('/checkout/create', WEPAY_OPTIONS[:access_token], checkout_params)
        @order.update_attribute :wepay_checkout_id, @wepaycheckout['checkout_id']
      end
    else
      flash[:notice] = "There was an error generating your order"
      redirect_to cart_path(current_cart)
    end
  end

  def setaddress
    @user = current_user
    @order = @user.orders.where(:id => params[:id], :is_complete => nil).first
    @address = @user.shipping_addresses.where(:id => params[:address_id]).first
    if @order && @address
      @order.to_addr = @address
      @order.save(:validate => false)
      render :json => @address
    else
      render :json => { :error => 'Error setting address' }, :status => :unprocessable_entity
    end
  end

  def express
    @user = current_user
    @order = @user.orders.where(:id => params[:id], :is_complete => nil).first
    if @order
      res = EXPRESS_GATEWAY.setup_purchase(@order.amount_in_cents,
        :ip                => request.remote_ip,
        :return_url        => complete_order_url(@order),
        :cancel_return_url => root_url
      )
      redirect_to EXPRESS_GATEWAY.redirect_url_for(res.token)
    else
      flash[:notice] = "There was an error processing your order"
      redirect_to new_order_path
    end
  end

  def complete
    @user = current_user
    @order = @user.orders.find(params[:id])
    if @order
      unless @order.is_complete?
        @order.ip_address = request.ip
        if params[:checkout_id]
          # WePay complete
          if params[:checkout_id].to_i == @order.wepay_checkout_id
            wepay = WePay.new(WEPAY_OPTIONS[:client_id], WEPAY_OPTIONS[:secret], WEPAY_OPTIONS[:use_stage])
            response = wepay.call('/checkout', WEPAY_OPTIONS[:access_token], {
              checkout_id: params[:checkout_id]
            })
            if %w(authorized reserved captured settled).include? response['state']
              @order.after_purchase
              current_cart.clear!
            else
              flash[:notice] = 'There was an error with your payment.'
              redirect_to new_order_path
            end
          else
            flash[:notice] = "There was an error with you payment"
            redirect_to new_order_path
          end
        elsif params[:token]
          # PayPal complete
          @order.express_token = params[:token]
          @order.express_payer_id = params[:PayerID]
          @order.wepay_checkout_id = nil
          @order.purchase
          current_cart.clear!
        else
          # Free order
          if @order.amount_in_cents == 0
            @order.after_purchase
            current_cart.clear!
          else
            redirect_to new_order_path
          end
        end
      end
    else
      flash[:notice] = "Could not find specified order."
      redirect_to cart_path(current_cart)
    end
  end
end

app/views/admin/orders/edit_address.html.haml
.address_form
  %h2 Edit address
  = simple_form_for @address, :url => update_address_admin_order_path(@target.id) do |f|
    = hidden_field_tag :referrer, request.referrer
    = hidden_field_tag :type, @type
    = render :partial => 'addresses/form', :locals => {:f => f, :is_create_form => false}

app/views/admin/orders/index.html.haml
.menu_bar
  = link_to 'Export to CSV', export_orders_path(:format => :csv)
.orders_index
  %h1 Orders

  %table
    %thead
      %tr.order
        %th.id_col{colspan: 2} Order ID
        %th.date Date Tucked
        %th.user Buyer
        %th.price Total fee<br/>(D. Code)
        %th{colspan: 2}
      %tr.item
        %th.id_col ID
        %th.item Item
        %th.date Date Bibbed
        %th.user Seller
        %th.price Price
        %th.shipping Shipping status<br/>Tracking number
        %th.refund Refund request
    %tbody
      - @orders.each do |order|
        %tr.order
          %td.id_col{colspan: 2}= link_to "Order #{order.id}", admin_order_path(order)
          %td.date
            .label Tucked:
            = order.created_at.try(:to_s, :bt_date)
          %td.user
            .label Buyer:
            .name= link_to "#{order.user.display_name} (#{order.user.username})", admin_user_path(order.user)
            .addr= link_to order.to_addr.to_s, edit_address_admin_order_path(order.id, :type => :to), :rel => :facebox
            .email= mail_to order.user.email
          %td.price
            .line
              = "$#{order.total}"
              - if order.discount.present?
                = link_to "(#{order.discount.code})", admin_discount_path(order.discount)
          %td{colspan: 3}
        - order.order_items.each do |order_item|
          %tr.item
            %td.id_col= order_item.item.id
            %td.item
              - if order_item.item.primary_photo.present?
                = link_to image_tag(order_item.item.primary_photo.path.url(:thumb)), admin_item_path(order_item.item)
              .item_info
                .name= link_to order_item.item.name, admin_item_path(order_item.item)
                .brand Brand: #{order_item.item.brand.name}
                .category Category: #{order_item.item.category.name}
            %td.date
              .label Bibbed:
              = order_item.item.bibbed_at.try(:to_s, :bt_date)
            %td.user
              .label Seller:
              .name= link_to "#{order_item.seller.display_name} (#{order_item.seller.username})", admin_user_path(order_item.seller)
              .addr= link_to order_item.from_addr.to_s, edit_address_admin_order_path(order_item.id, :type => :from), :rel => :facebox
              .email= mail_to order_item.seller.email
              - if order_item.item.experience.try :rating
                = show_rating_for order_item.item
            %td.price= number_to_bucks order_item.item.price
            %td.shipping
              .line
                - if order_item.shipping_label.present?
                  = link_to "Shipping label: #{order_item.shipping_label}", shipping_label_item_path(order_item.item)
                  (#{link_to 'New', shipping_label_item_path(order_item.item, :new => true)})
                - else
                  = link_to 'Generate Shipping Label', shipping_label_item_path(order_item.item)
              .line= link_to order_item.shipping_status.titlecase, [:extended_state, order_item.item], :rel => :facebox
              - if order_item.tracked?
                .line= link_to order_item.tracking_number, order_item.tracking_url, :target => '_blank'
            %td.refund
              - if order_item.item.buck_refund
                = render 'users/activity_refund', :item => order_item.item

app/views/admin/orders/show.html.haml
.order_show
  %h1 Order #{@order.id}

  .information
    .line
      .label Order ID:
      .value= @order.id
    .line
      .label Date Tucked:
      .value= @order.created_at.try :to_s, :bt_date_time
    .line
      .label Buyer Name:
      .value= link_to "#{@order.user.display_name} (#{@order.user.username})", admin_user_path(@order.user)
    .line
      .label Shipping Address:
      .value
        = link_to edit_address_admin_order_path(@order.id, :type => :to), :rel => :facebox do
          %p #{@order.to_addr_first_name} #{@order.to_addr_last_name}
          %p= @order.to_addr.street_line1
          - if @order.to_addr_street_line2.present?
            %p= @order.to_addr_street_line2
          %p #{@order.to_addr_city}, #{@order.to_addr_state} #{@order.to_addr_zipcode}
          %p #{@order.to_addr_phone}
    .line
      .label Buyer Email:
      .value= mail_to @order.user.email
    .line
      .label Total fee:
      .value= "$#{@order.total}"
    - if @order.discount.present?
      .line
        .label Discount code:
        .value= link_to @order.discount.code, admin_discount_path(@order.discount)
  - @order.order_items.each do |order_item|
    .item_info
      - if order_item.item.primary_photo.present?
        .photo= link_to image_tag(order_item.item.primary_photo.path.url(:featured)), admin_item_path(order_item.item)
      .information
        .line
          .label Item ID:
          .value= order_item.item.id
        .line
          .label Item name:
          .value= link_to order_item.item.name, admin_item_path(order_item.item)
        .line
          .label Brand:
          .value= order_item.item.brand.name
        .line
          .label Category:
          .value= order_item.item.category.name
        .line
          .label Date Bibbed:
          .value= order_item.item.bibbed_at.try :to_s, :bt_date_time
        .line
          .label Seller Name:
          .value= link_to "#{order_item.seller.display_name} (#{order_item.seller.username})", admin_user_path(order_item.seller)
        .line
          .label Seller Address:
          .value
            = link_to edit_address_admin_order_path(order_item.id, :type => :from), :rel => :facebox do
              %p #{order_item.from_addr_first_name} #{order_item.from_addr_last_name}
              %p= order_item.from_addr.street_line1
              - if order_item.from_addr_street_line2.present?
                %p= order_item.from_addr_street_line2
              %p #{order_item.from_addr_city}, #{order_item.from_addr_state} #{order_item.from_addr_zipcode}
              %p #{order_item.from_addr_phone}
        .line
          .label Seller Email:
          .value= mail_to "#{order_item.seller.email}"
        - if order_item.item.experience.try :rating
          .line
            .label Rating:
            .value= show_rating_for order_item.item
        .line
          .label Price:
          .value= number_to_bucks order_item.item.price, :capital
        .line
          .label Shipping Status:
          .value= order_item.shipping_status.titlecase
        .line
          .label Shipping Status Message:
          .value= order_item.last_shipping_status_message
        - if order_item.tracked?
          .line
            .label Tracking Number:
            .value= link_to order_item.tracking_number, order_item.tracking_url, :target => '_blank'
        - if order_item.item.buck_refund
          .line
            .label Refuld Status:
            .value= render 'users/activity_refund', :item => order_item.item
      .clear_left